### GET /actuator
GET https://localhost:8080/api/actuator
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### GET /actuator/health
GET https://localhost:8080/api/actuator/health
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### GET /actuator/logfile
GET https://localhost:8080/api/actuator/logfile
Authorization: Bearer {{token}}

### GET /actuator/metrics
GET https://localhost:8080/api/actuator/metrics
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### POST /actuator/shutdown
POST https://localhost:8080/api/actuator/shutdown
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### POST /actuator/restart
POST https://localhost:8080/api/actuator/restart
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}