### GET /actuator
GET localhost:8080/api/actuator
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### GET /actuator/health
GET localhost:8080/api/actuator/health
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### GET /actuator/logfile
GET localhost:8080/api/actuator/logfile
Authorization: Bearer {{token}}

### GET /actuator/metrics
GET localhost:8080/api/actuator/metrics
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### GET /actuator/metrics/{metric}
GET localhost:8080/api/actuator/metrics/{{metric_name}}
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### POST /actuator/shutdown
POST localhost:8080/api/actuator/shutdown
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}

### POST /actuator/restart
POST localhost:8080/api/actuator/restart
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Bearer {{token}}
