### GET /admin
GET localhost:8080/api/admin
Authorization: Bearer {{token}}

### GET /admin/user
GET localhost:8080/api/admin/user
Authorization: Bearer {{token}}

### GET /admin/user/{uid}
GET localhost:8080/api/admin/user/{{target_uid}}
Authorization: Bearer {{token}}

### POST /admin/user/{uid}/enable
POST localhost:8080/api/admin/user/{{target_uid}}/enable
Authorization: Bearer {{token}}

### POST /admin/user/{uid}/disable
POST localhost:8080/api/admin/user/{{target_uid}}/disable
Authorization: Bearer {{token}}

### POST /admin/user/{uid}/promote
POST localhost:8080/api/admin/user/{{target_uid}}/promote
Authorization: Bearer {{token}}

### POST /admin/user/{uid}/demote
POST localhost:8080/api/admin/user/{{target_uid}}/demote
Authorization: Bearer {{token}}

### GET /admin/task/stats
GET localhost:8080/api/admin/task/stats
Authorization: Bearer {{token}}

### GET /admin/configuration
GET localhost:8080/api/admin/configuration
Authorization: Bearer {{token}}
Content-Type: application/json

### POST /admin/configuration
POST localhost:8080/api/admin/configuration
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "request_limit" : 3,
  "task_runner_count": 1,
  "repo_maintainer_cron": "0 0 0 * * SUN"
}
