### GET /user
GET localhost:8080/api/user
Authorization: Bearer {{token}}

### GET /user/{uid}
GET localhost:8080/api/user/{{target_uid}}
Authorization: Bearer {{token}}

### POST /user/register
POST localhost:8080/api/user/register
Content-Type: application/json

{
  "email": "dozren@yahoo.com",
  "password": "Lugano2022",
  "organisation": "USI"
}

### POST /user/login
POST localhost:8080/api/user/login
Content-Type: application/json

{
  "email": "dozren@yahoo.com",
  "password": "Lugano2022"
}

### GET /user/verify
GET localhost:8080/api/user/verify?token={{verify_token}}

### GET /user/verify/resend
GET localhost:8080/api/user/verify/resend?token={{verify_token}}

### POST /user/password/forgotten
POST localhost:8080/api/user/password/forgotten
Content-Type: application/json

{
  "email": "dozren@yahoo.com"
}

### POST /user/password/reset
POST localhost:8080/api/user/password/reset?token={{pass_reset_token}}
Content-Type: application/json

{
  "password": "22022onaguL"
}

### PUT /user/uid
PUT localhost:8080/api/user/uid
Content-Type: text/plain;charset=UTF-8
Authorization: Bearer {{token}}

ozozozoz

### PUT /user/email
PUT localhost:8080/api/user/email
Content-Type: text/plain;charset=UTF-8
Authorization: Bearer {{token}}

ozren.dabic@usi.ch

### PUT /user/organisation
PUT localhost:8080/api/user/organisation
Content-Type: text/plain;charset=UTF-8
Authorization: Bearer {{token}}

Università della Svizzera italiana
