#!/usr/bin/env bash

psql -U postgres -c "
CREATE ROLE $DATABASE_USER WITH
ENCRYPTED PASSWORD '$DATABASE_PASS'
LOGIN NOSUPERUSER CREATEDB NOCREATEROLE INHERIT NOREPLICATION
CONNECTION LIMIT -1;" \
&& \
psql -U postgres -c "
CREATE DATABASE $DATABASE_NAME WITH
OWNER = $DATABASE_USER
ENCODING = 'UTF8'
CONNECTION LIMIT = -1;"
