DROP TABLE "databasechangeloglock";
DROP TABLE "databasechangelog";
DROP TABLE "crawl_job";
DROP TABLE "function";
DROP TABLE "file";
DROP TABLE "git_repo_language";
DROP TABLE "language";
DROP TABLE "git_repo";
DROP SEQUENCE "hibernate_sequence";
