@startuml cleanup
title Dataset Maintainance

skinparam SequenceGroupBodyBackgroundColor #FFFFFF00
skinparam shadowing false

box "DL4SE" #LightGray
    participant "Database" as DB
    participant "Cleaner" as DL4SE
end box

participant "GHS API" as GHS

loop every X hours
    DL4SE -\ DB: find all
    DB -/ DL4SE

    loop for each repository
        DL4SE -> GHS: GET /api/r/{name}
        alt #LightGreen repository exists
            GHS -> DL4SE: 200
        else #LightCoral repository deleted
            GHS -> DL4SE: 404
            DL4SE -> DB: flag repository
        end
    end
end

@enduml