name: 'Build Java files with Maven'

on:
  push:
    branches: [ 'main' ]
    paths: [ '**/*.java' ]
  pull_request:
    branches: [ 'main' ]
    paths: [ '**/*.java' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: 11
          java-distribution: 'temurin'
      - name: Build with Maven
        run:  mvn -e --no-transfer-progress package
