name: Vue Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dl4se-website
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: './dl4se-website/package-lock.json'

      - name: Node Clean Install
        run: npm clean-install

      - name: Lint
        run: npm run lint

      - name: Vue Build
        run: npm run build --if-present
