name: 'Build Vue project'

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.js'
      - '**/*.vue'
      - '**/*.json'
      - '**/*.sass'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**/*.js'
      - '**/*.vue'
      - '**/*.json'
      - '**/*.sass'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dl4se-website
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Vue Build
        run: npm run build
